### ISSUE TITLE
Telephone numbers in +155500000 form fail to validate.

### ISSUE THREAD

**Issue by cluck** [doappweb/DaVueTheme#4]
In the profile view, the form fails to validate when telephone numbers follow the international format with a leading "+", e.g. "+155500000".

**Comment by doappweb** [comment]
Hello, cluck!
Thanks for the comment, but that's what we had in mind. 
When implemented in other projects for ours, more often it all came down to the case - 'write down only numbers'.  
Moreover, it is correct to write numbers in the database. And for example, when implementing click-to-call, substitute '+' at the beginning automatically.

Perhaps in the future we will implement a custom mask for phones.

**Comment by cluck** [comment]
How it's stored shouldn't be related to how it's displayed, and the problem I reported is with the latter.

But as you mention storage, you can't build a software to properly deal with telephone numbers without systematically converting them to the plus-prefixed internation format for storage. Only when you do that, and if you fully control all writes on the database, then you may strip the plus sign in front of the stored numbers. But remember that `*`, `#`, `~` are valid telephone number components too, thus a text field it will remain.

Back to the UI representation: you need a library to properly internationalize and localize these numbers based on the region and instant in which your (software) client is currently dialing or interpreting the numbers. And not being able to just pass in and obtain the international numbers is very odd from an European point of view, as we usually work with just these all the time, especially in business.

Relevant standards are ITU E.123 and ITU E.164.

**Comment by doappweb** [comment]
Having experience in implementing SuiteCRM-based projects around the world, I can answer the following:

- you forgot about national and stationary formats (where there is no "+" at all)
- automatic conversion to the desired format - standard practice when integrating telephony
- that is why, as a universal format, "only numbers" was taken as the basis

And as I answered above, all these cases are covered by a customizable individual mask for displaying and entering the number =)

**Comment by cluck** [comment]
Oh, well.

**Comment by cluck** [comment]
Oh, well.
